### ISSUE TITLE
The calendar doesn't get updated after clear bookings

### ISSUE THREAD

**Issue by JosueVidaur** [simpletut/reactjs-availability-calendar#12]
I stored all of my booked days and I have a useEffect hook that gets triggered after a request is sent to archive those booked days, the state gets updated but the calendar still shows the bookings. So, the code is something like this:

```
import Calendar from 'reactjs-availability-calendar'
const CalendarComponent = () => {
  const [bookedDays, setBookedDays] = useState([]);
  const [removeBookedDays, removeBookedDaysResponse] = useRemoveBookedDaysMutation() // redux toolkit
  useEffect(() => {
    if(removeBookedDaysResponse.isSuccess)
    setBookedDays([])
  }, [removeBookedDaysResponse])
  return (
    <Calendar
      bookings={bookedDays}
    />
  )
}
```

it works just if I have multiple bookings and I remove them one at a time, but when I try to remove the last one or all at once the Calendar doesn't get updated

**Comment by simpletut** [comment]
This issue has been fixed. 

Please upgrade to `v.1.1.7`
